### ISSUE TITLE
DL is deprecated, please use Fiddle

### ISSUE THREAD

**Issue by pbearne** [mislav/git-deploy#67]
Got this when running git deploy setup -r "production"

looks like it fails

running on windows 8 in git bash shell mingw32

```
DL is deprecated, please use Fiddle
c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/packet_s
tream.rb:103:in `block in next_packet': connection closed by remote host (Net::S
SH::Disconnect)
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/packet_stream.rb:93:in `loop'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/packet_stream.rb:93:in `next_packet'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/session.rb:172:in `block in poll_message'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/session.rb:167:in `loop'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/session.rb:167:in `poll_message'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/trans
port/session.rb:152:in `next_message'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:94:in `block in next_message'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:93:in `loop'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:93:in `next_message'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/methods/publickey.rb:53:in `authenticate_with'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/methods/publickey.rb:20:in `block in authenticate'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/key_manager.rb:111:in `block in each_identity'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/key_manager.rb:103:in `each'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/key_manager.rb:103:in `each_identity'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/methods/publickey.rb:19:in `authenticate'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:78:in `block in authenticate'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:65:in `each'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh/authe
ntication/session.rb:65:in `authenticate'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:19
6:in `start'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/git-deploy-0.6.1/lib/git_deploy
/ssh_methods.rb:96:in `ssh_connection'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/git-deploy-0.6.1/lib/git_deploy
/ssh_methods.rb:43:in `ssh_exec'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/git-deploy-0.6.1/lib/git_deploy
/ssh_methods.rb:35:in `run_test'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/git-deploy-0.6.1/lib/git_deploy
.rb:28:in `setup'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.14.6/lib/thor/task.rb:22
:in `run'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.14.6/lib/thor/invocation
.rb:118:in `invoke_task'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.14.6/lib/thor.rb:263:in
`dispatch'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.14.6/lib/thor/base.rb:38
9:in `start'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/git-deploy-0.6.1/bin/git-deploy
:3:in `<top (required)>'
        from c:/Ruby200/bin/git-deploy:23:in `load'
        from c:/Ruby200/bin/git-deploy:23:in `<main>'
```

**Comment by sesam** [comment]
suggest close: Mostly answered already. Any more on this topic, please try a support forum. Maybe one linked here: https://stackexchange.com/sites
