### ISSUE TITLE
git-deploy fails on Windows

### ISSUE THREAD

**Issue by lhall-adexos** [mislav/git-deploy#80]
I'm having trouble using this gem on Windows because of the net-ssh version required. The net-ssh version installed along gi-deploy is `2.6.8`, and throws an error. If I use a Gemfile with gem `"net-ssh", "3.0.2"` it does work, but I end up with git-deploy 0.5.4.

Is it possible to update the gem requirements ?

Error thrown :

`C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dl/import (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/pageant.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/agent/socket.rb:5:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/agent.rb:22:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/key_manager.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:11:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git-deploy-0.6.1/lib/git_deploy.rb:2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git-deploy-0.6.1/bin/git-deploy:2:in `<top (required)>'
        from C:/Ruby22/bin/git-deploy:23:in `load'
        from C:/Ruby22/bin/git-deploy:23:in `<main>'
`

**Comment by Xtremefaith** [comment]
Has this issue made any progress? I'm on Windows 7, Gem 2.6.8, Ruby 2.3.1p112 and still having this issue as well:

```
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- dl/import (LoadError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/pageant.rb:1:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/agent/socket.rb:5:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/agent.rb:22:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/key_manager.rb:4:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh/authentication/session.rb:4:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:11:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/git-deploy-0.6.1/lib/git_deploy.rb:2:in '<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/git-deploy-0.6.1/bin/git-deploy:2:in '<top (required)>'
        from C:/Ruby23/bin/git-deploy:22:in 'load'
        from C:/Ruby23/bin/git-deploy:22:in '<main>'

**Comment by mislav** [comment]
I'm sorry about you having trouble. There was https://github.com/mislav/git-deploy/pull/74 which relaxes the net-ssh version constraint, but still doesn't allow it to be updated to net-ssh 3. I'm not sure if net-ssh 2.9 would be enough.

Can one of you just try installing the latest net-ssh `< 3.0` on their machine, then `require "net/ssh"` and see if the issue goes away? If so, then I can just make a release with the version of git-deploy in master.
