### ISSUE TITLE
Net::SSH::AuthenticationFailed

### ISSUE THREAD

**Issue by mahendhar9** [mislav/git-deploy#81]
Hello.
I get the following error on running `git deploy setup -r "production"`

```
/home/mahendhar/.rvm/gems/ruby-2.2.2/gems/net-ssh-2.6.6/lib/net/ssh.rb:201:in `start': root (Net::SSH::AuthenticationFailed)
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:96:in `ssh_connection'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:43:in `ssh_exec'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:35:in `run_test'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/git-deploy-0.6.1/lib/git_deploy.rb:28:in `setup'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/gems/git-deploy-0.6.1/bin/git-deploy:3:in `<top (required)>'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/bin/git-deploy:23:in `load'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/bin/git-deploy:23:in `<main>'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/mahendhar/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```
I even updated the net-ssh gem version, but the problem persists. Can anyone kindly help?

**Comment by philliprauschkolb** [comment]
Same issue here

**Comment by mahendhar9** [comment]
@philliprauschkolb I followed this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps) for automatic git deployment. The tutorial doesn't use   this gem.

**Comment by peterhoffren** [comment]
Same issue here, osx sierra
