### ISSUE TITLE
Can't  git deploy setup -r "production" (MacOS Sierra)

### ISSUE THREAD

**Issue by kentuck13** [mislav/git-deploy#88]
`
Alexander:src alexander$ git deploy setup -r "live"
/Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:78:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/cipher_factory.rb:98: warning: constant OpenSSL::Cipher::Cipher is deprecated
/Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:118:in `generate_key': undefined method `p=' for #<OpenSSL::PKey::DH:0x007f880f172020> (NoMethodError)
Did you mean?  p
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:51:in `initialize'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:348:in `new'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:348:in `exchange_keys'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:196:in `proceed!'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:187:in `send_kexinit'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:142:in `accept_kexinit'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:189:in `block in poll_message'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `loop'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `poll_message'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:204:in `block in wait'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `loop'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `wait'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:81:in `initialize'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `new'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `start'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:96:in `ssh_connection'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:43:in `ssh_exec'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:35:in `run_test'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/git-deploy-0.6.1/lib/git_deploy.rb:28:in `setup'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/gems/git-deploy-0.6.1/bin/git-deploy:3:in `<top (required)>'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/bin/git-deploy:23:in `load'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/bin/git-deploy:23:in `<main>'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alexander/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
`

**Comment by javiernunez** [comment]
I had the same problem and it seeems to be related with Ruby version. 4.2.2 should work.

**Comment by Shakthijuego** [comment]
Issue is not solved even after updating ruby.

However I found git-deploy no longer needed after git introduced  **push to deploye**
https://blog.github.com/2015-02-06-git-2-3-has-been-released/#push-to-deploy
