### ISSUE TITLE
Problems when setting up deployment

### ISSUE THREAD

**Issue by javiernunez** [mislav/git-deploy#90]
I'm having this problem when running git deploy setup. My command is:

`git deploy setup -r staging`

The result:
```
/home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:67: warning: Object#timeout is deprecated, use Timeout.timeout instead.
/home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:78: warning: Object#timeout is deprecated, use Timeout.timeout instead.
/home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/cipher_factory.rb:98: warning: constant OpenSSL::Cipher::Cipher is deprecated
Traceback (most recent call last):
	26: from /home/javisquare1/.rbenv/versions/2.5.1/bin/git-deploy:23:in `<main>'
	25: from /home/javisquare1/.rbenv/versions/2.5.1/bin/git-deploy:23:in `load'
	24: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/git-deploy-0.6.1/bin/git-deploy:3:in `<top (required)>'
	23: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
	22: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
	21: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
	20: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
	19: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/git-deploy-0.6.1/lib/git_deploy.rb:28:in `setup'
	18: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:35:in `run_test'
	17: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:43:in `ssh_exec'
	16: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/git-deploy-0.6.1/lib/git_deploy/ssh_methods.rb:96:in `ssh_connection'
	15: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `start'
	14: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `new'
	13: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:81:in `initialize'
	12: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `wait'
	11: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `loop'
	10: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:204:in `block in wait'
	 9: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `poll_message'
	 8: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `loop'
	 7: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:189:in `block in poll_message'
	 6: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:142:in `accept_kexinit'
	 5: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:187:in `send_kexinit'
	 4: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:196:in `proceed!'
	 3: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:348:in `exchange_keys'
	 2: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/algorithms.rb:348:in `new'
	 1: from /home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:51:in `initialize'
/home/javisquare1/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-ssh-2.6.8/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:118:in `generate_key': undefined method `p=' for #<OpenSSL::PKey::DH:0x000055b7e7635778> (NoMethodError)
Did you mean?  p

```

My guess is that the problem is with 'net-ssh' version but, as the dependency is fixed to "~2.6" I can't upgrade it. Does anyone know how to fix this?

I'm on Ubuntu 18.04 and these are my packages versions:
Ruby          2.5.1p57
git-deploy (0.6.1)
net-ssh (2.6.8)

**Comment by javiernunez** [comment]
I solved the problem. It was the Ruby version. Right now, I downgraded Ruby version from 2.5.1 to 4.2.2 and it's working now.
